Feature/km 18 add GitHub actions
katapultmedia/terraform-tfc-workspace pull request #3
Opened 2020-07-08 14:26 UTC by warrenbrown

2020-07-09 13:59 UTC, johncblandii requested changes

2020-07-09 13:59 UTC, johncblandii commented on .github/workflows/pre-commit.yaml
> +        curl -L "$(curl -s https://api.github.com/repos/terraform-linters/tflint/releases/latest | grep -o -E "https://.+?_linux_amd64.*zip")" > tflint.zip
```suggestion
        curl -L "$(curl -Ls https://api.github.com/repos/terraform-linters/tflint/releases/latest | grep -o -E "https://.+?_linux_amd64.*zip")" > tflint.zip
```

2020-07-09 13:59 UTC, johncblandii commented on .github/workflows/terraform.yaml
> +    name: Check terraform file are formatted correctly
Seems like a lot of duplication here for fmt.

2020-07-12 14:46 UTC, warrenbrown commented
I added that main.tf file for testing purposes for the terraform GitHub actions workflow.  I needed some sort of terraform file in there to make sure the terraform init step would trigger I will delete after you review and notate any needed changes @johncblandii

2020-07-17 22:23 UTC, johncblandii submitted a review, later dismissed

2020-07-20 22:42 UTC, johncblandii approved these changes

2020-07-20 22:43 UTC, merged